/**
 * build-css.ts — emits dist/tokens.css and dist/theme.css from the compiled
 * primitive + semantic TS sources.
 *
 * Per ADR-0012, TypeScript is the canonical source of truth. This script is
 * intentionally dependency-free (only Node built-ins + Node types) and is
 * compiled to JS first by `tsc -p tsconfig.build.json`, then executed by
 * plain `node`. No `tsx` or `ts-node` runtime needed.
 *
 * CSS variable names follow Tailwind v4 canonical conventions:
 *   - colors:        --color-<path>            (e.g. --color-bg-app)
 *   - spacing:       --spacing-<key>           (e.g. --spacing-4)
 *   - radii:         --radius-<key>            (e.g. --radius-md)
 *   - font family:   --font-<key>              (e.g. --font-sans)
 *   - font size:     --text-<key>              (e.g. --text-base)
 *   - font weight:   --font-weight-<key>
 *   - line height:   --leading-<key>
 *   - duration:      --duration-<key>
 *   - easing:        --ease-<key>
 *
 * No `--rhitta-*` vendor prefix.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { colors, motion, radii, spacing, typography } from '../src/primitive.js'
import { semantic } from '../src/semantic.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const DIST_DIR = resolve(HERE, '..')

type CssDecl = { name: string; value: string }

function kebab(input: string): string {
  return input.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)
}

function pushColor(out: CssDecl[], path: string[], value: string): void {
  out.push({ name: `--color-${path.map(kebab).join('-')}`, value })
}

function collectPrimitives(): CssDecl[] {
  const out: CssDecl[] = []

  // colors.brand.*
  for (const [key, value] of Object.entries(colors.brand)) {
    pushColor(out, ['brand', key], value)
  }
  // colors.neutral.<scale>
  for (const [key, value] of Object.entries(colors.neutral)) {
    pushColor(out, ['neutral', key], value)
  }
  // colors.semantic.<role>  → --color-<role> (status colors live at the top
  // level in Tailwind's canonical naming, not under a `semantic-` namespace)
  for (const [key, value] of Object.entries(colors.semantic)) {
    pushColor(out, [key], value)
  }

  // spacing
  for (const [key, value] of Object.entries(spacing)) {
    out.push({ name: `--spacing-${key}`, value })
  }

  // radii
  for (const [key, value] of Object.entries(radii)) {
    out.push({ name: `--radius-${key}`, value })
  }

  // typography.fontFamily
  for (const [key, value] of Object.entries(typography.fontFamily)) {
    out.push({ name: `--font-${kebab(key)}`, value })
  }
  // typography.fontSize → --text-<key>
  for (const [key, value] of Object.entries(typography.fontSize)) {
    out.push({ name: `--text-${kebab(key)}`, value })
  }
  // typography.fontWeight
  for (const [key, value] of Object.entries(typography.fontWeight)) {
    out.push({ name: `--font-weight-${kebab(key)}`, value: String(value) })
  }
  // typography.lineHeight → --leading-<key>
  for (const [key, value] of Object.entries(typography.lineHeight)) {
    out.push({ name: `--leading-${kebab(key)}`, value: String(value) })
  }

  // motion.duration
  for (const [key, value] of Object.entries(motion.duration)) {
    out.push({ name: `--duration-${kebab(key)}`, value })
  }
  // motion.easing
  for (const [key, value] of Object.entries(motion.easing)) {
    out.push({ name: `--ease-${kebab(key)}`, value })
  }

  return out
}

type SemanticDecls = { light: CssDecl[]; dark: CssDecl[] }

function collectSemantics(): SemanticDecls {
  const light: CssDecl[] = []
  const dark: CssDecl[] = []

  for (const [groupKey, group] of Object.entries(semantic)) {
    for (const [leafKey, themed] of Object.entries(group)) {
      const name = `--color-${kebab(groupKey)}-${kebab(leafKey)}`
      light.push({ name, value: themed.light })
      dark.push({ name, value: themed.dark })
    }
  }

  return { light, dark }
}

function renderBlock(selector: string, decls: CssDecl[]): string {
  const body = decls.map((d) => `  ${d.name}: ${d.value};`).join('\n')
  return `${selector} {\n${body}\n}`
}

function renderTokensCss(primitives: CssDecl[], semantics: SemanticDecls): string {
  const rootDecls = [...primitives, ...semantics.light]
  const lines = [
    '/* Generated by @rhitta/design-tokens. Do not edit by hand. */',
    '/* Source of truth: src/primitive.ts + src/semantic.ts. */',
    '',
    renderBlock(':root', rootDecls),
    '',
    renderBlock('[data-theme="dark"]', semantics.dark),
    '',
  ]
  return lines.join('\n')
}

function renderThemeCss(primitives: CssDecl[], semantics: SemanticDecls): string {
  // Tailwind v4 @theme block aliases each token to its var(). The semantic
  // entries take their light name (the name is identical in dark, only the
  // value differs), so we dedupe by name.
  const seen = new Set<string>()
  const mappings: string[] = []
  const push = (name: string) => {
    if (seen.has(name)) return
    seen.add(name)
    mappings.push(`  ${name}: var(${name});`)
  }
  for (const d of primitives) push(d.name)
  for (const d of semantics.light) push(d.name)

  const lines = [
    '/* Generated by @rhitta/design-tokens. Do not edit by hand. */',
    '/* Source of truth: src/primitive.ts + src/semantic.ts. */',
    '',
    '@theme {',
    mappings.join('\n'),
    '}',
    '',
  ]
  return lines.join('\n')
}

async function main(): Promise<void> {
  const primitives = collectPrimitives()
  const semantics = collectSemantics()

  const tokensCss = renderTokensCss(primitives, semantics)
  const themeCss = renderThemeCss(primitives, semantics)

  await mkdir(DIST_DIR, { recursive: true })

  const tokensPath = resolve(DIST_DIR, 'tokens.css')
  const themePath = resolve(DIST_DIR, 'theme.css')

  await writeFile(tokensPath, tokensCss, 'utf-8')
  await writeFile(themePath, themeCss, 'utf-8')

  const semanticCount = semantics.light.length
  console.log(
    `[design-tokens] wrote ${primitives.length} primitives + ${semanticCount} semantic ` +
      `tokens to:\n  - ${tokensPath}\n  - ${themePath}`
  )
}

main().catch((err: unknown) => {
  console.error('[design-tokens] build-css failed:', err)
  process.exit(1)
})
