// =============================================================================
// api-client/index.ts — public re-export hub.
// =============================================================================
//
// Consumers import from `~/lib/api-client/`, never from `./api-client.js`
// directly. This keeps the import surface stable when the underlying file
// changes (e.g., regenerated by `encore gen client`).
//
// Per ADR-0020, all API call sites must go through TanStack Query wrappers
// in `~/lib/queries/<domain>.ts`; components do not import this module.
// =============================================================================

export * from './api-client.js'
