#!/usr/bin/env bash
set -euo pipefail

# rhitta-overlay.sh — idempotent post-install patch script.
# Applies Rhitta conventions on top of an Ignite-scaffolded app.
# Run after: npx ignite-cli new mobile --bundle com.rhitta.app --no-git
# Idempotent: safe to run twice. Writes .rhitta-overlay-applied marker.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$(dirname "$SCRIPT_DIR")"
OVERLAY_VERSION="0.1.0"

echo "[rhitta-overlay] v$OVERLAY_VERSION — applying Rhitta conventions..."

cd "$APP_DIR"

# ---- 0. Idempotency guard ----
MARKER="$APP_DIR/.rhitta-overlay-applied"
if [ -f "$MARKER" ]; then
  APPLIED=$(head -n1 "$MARKER")
  if [ "$APPLIED" = "$OVERLAY_VERSION" ]; then
    echo "[rhitta-overlay] v$OVERLAY_VERSION already applied. Skipping."
    exit 0
  fi
  echo "[rhitta-overlay] upgrading from $APPLIED to $OVERLAY_VERSION..."
fi

# ---- 1. Update package.json ----
echo "[rhitta-overlay] Updating package.json..."
node -e '
const fs = require("fs");
const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
pkg.name = "@rhitta/mobile";
pkg.private = true;
// Remove MST/MobX deps
delete pkg.dependencies["mobx"];
delete pkg.dependencies["mobx-react-lite"];
delete pkg.dependencies["mobx-state-tree"];
// Remove MST/MobX devDeps
delete pkg.devDependencies["mobx"];
delete pkg.devDependencies["mobx-state-tree"];
// Add Biome & Tsconfig deps for config resolution
pkg.devDependencies["@rhitta/biome-config"] = "workspace:*";
pkg.devDependencies["@rhitta/tsconfig"] = "workspace:*";
// Add Rhitta workspace deps
pkg.dependencies["@rhitta/design-tokens"] = "workspace:*";
pkg.dependencies["@rhitta/contracts"] = "workspace:*";
pkg.dependencies["@rhitta/design-system-mobile"] = "workspace:*";
pkg.dependencies["@tanstack/react-query"] = "^5.0.0";
pkg.dependencies["@tanstack/react-form"] = "^1.0.0";
pkg.dependencies["zustand"] = "^5.0.0";
pkg.dependencies["better-auth"] = "^1.0.0";
pkg.dependencies["expo-router"] = "^4.0.0";
pkg.dependencies["expo-secure-store"] = "^14.0.0";
fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2) + "\n");
console.log("package.json updated.");
'

# ---- 2. Strip MST models ----
echo "[rhitta-overlay] Stripping MST models..."
rm -rf app/models 2>/dev/null || true

# ---- 3. Strip Ignite navigators / example screens ----
echo "[rhitta-overlay] Stripping Ignite navigators and example screens..."
rm -rf app/navigators 2>/dev/null || true
rm -rf app/screens 2>/dev/null || true
rm -f app/screens/*.tsx 2>/dev/null || true

# ---- 4. Create Rhitta directory structure ----
echo "[rhitta-overlay] Creating Rhitta directory structure..."
mkdir -p app/auth
mkdir -p app/_authenticated/notes/\[noteId\]
mkdir -p src/lib/api-client
mkdir -p src/lib/auth
mkdir -p src/lib/queries
mkdir -p src/lib/realtime
mkdir -p src/lib/theme
mkdir -p src/lib/toasts
mkdir -p scripts

# ---- 5. Inject Rhitta config files ----
echo "[rhitta-overlay] Injecting Rhitta configs..."

# tsconfig.json
cat > tsconfig.json << 'TSEOF'
{
  "extends": "@rhitta/tsconfig/mobile.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "baseUrl": ".",
    "paths": {
      "~/*": ["./src/*"],
      "@/*": ["./app/*"],
      "@assets/*": ["./assets/*"]
    }
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules", "dist", ".expo"]
}
TSEOF

# biome.json
cat > biome.json << 'BIOMEEOF'
{
  "$schema": "https://biomejs.dev/schemas/2.4.16/schema.json",
  "root": false,
  "extends": [
    "@rhitta/biome-config/base",
    "@rhitta/biome-config/react",
    "@rhitta/biome-config/mobile-app"
  ],
  "linter": {
    "rules": {
      "correctness": {
        "noUndeclaredDependencies": "off",
        "useHookAtTopLevel": "off"
      },
      "performance": {
        "noAccumulatingSpread": "off"
      },
      "complexity": {
        "noBannedTypes": "off"
      },
      "suspicious": {
        "noExplicitAny": "off",
        "noImplicitAnyLet": "off"
      }
    }
  }
}
BIOMEEOF

# ---- 6. Patch theme to use design-tokens ----
echo "[rhitta-overlay] Patching theme to use @rhitta/design-tokens..."
if [ -f app/theme/colors.ts ]; then
  cat > app/theme/colors.ts << 'COLORSEOF'
// Auto-generated by rhitta-overlay.sh — imports from @rhitta/design-tokens.
// Do not hand-edit theme values here; edit @rhitta/design-tokens instead.
export { semantic as colors } from '@rhitta/design-tokens/semantic';
COLORSEOF
fi

if [ -f app/theme/typography.ts ]; then
  cat > app/theme/typography.ts << 'TYPOEOF'
// Auto-generated by rhitta-overlay.sh — imports from @rhitta/design-tokens.
export { typography } from '@rhitta/design-tokens/semantic';
TYPOEOF
fi

if [ -f app/theme/spacing.ts ]; then
  cat > app/theme/spacing.ts << 'SPACEOF'
// Auto-generated by rhitta-overlay.sh — imports from @rhitta/design-tokens.
export { spacing } from '@rhitta/design-tokens/semantic';
SPACEOF
fi

# ---- 7. Patch metro.config.js for pnpm monorepo ----
echo "[rhitta-overlay] Patching metro.config.js for pnpm monorepo..."
node -e '
const fs = require("fs");
let metro = fs.readFileSync("metro.config.js", "utf8");
// If watchFolders is not already set, inject the pnpm-compatible config
if (!metro.includes("watchFolders")) {
  const patch = `
// Rhitta overlay: Metro pnpm monorepo resolution.
// Metro must traverse symlinked workspace deps; default Metro config does not.
const { getDefaultConfig } = require("expo/metro-config");
const path = require("path");
const repoRoot = path.resolve(__dirname, "../..");
const defaultConfig = getDefaultConfig(__dirname);
defaultConfig.watchFolders = [repoRoot, path.resolve(__dirname, "node_modules")];
defaultConfig.resolver.nodeModulesPaths = [
  path.resolve(__dirname, "node_modules"),
  path.resolve(repoRoot, "node_modules"),
];
module.exports = defaultConfig;
`;
  fs.writeFileSync("metro.config.js", patch);
  console.log("metro.config.js patched for pnpm monorepo.");
} else {
  console.log("metro.config.js already has watchFolders — skipping.");
}
'

# ---- 8. Write idempotency marker ----
echo "$OVERLAY_VERSION" > "$MARKER"
echo "[rhitta-overlay] Done. Rhitta conventions applied (v$OVERLAY_VERSION)."
