// Auto-generated by rhitta-overlay.sh — imports from @rhitta/design-tokens.
// Do not hand-edit theme values here; edit @rhitta/design-tokens instead.
export { semantic as colors } from '@rhitta/design-tokens/semantic'
